# Generated by Django 2.0.3 on 2018-03-22 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('difficulty', models.IntegerField(default=75)),
                ('rating', models.IntegerField(default=0)),
                ('num_answers', models.IntegerField(default=0)),
                ('answers', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'riddles',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tries', models.IntegerField(default=0)),
                ('correct', models.BooleanField(default=False)),
                ('answer', models.CharField(default='', max_length=30)),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddlr.Riddle')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('karma', models.IntegerField(default=0)),
                ('guess_ratio', models.FloatField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('riddles', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddlr.UserProfile'),
        ),
        migrations.AddField(
            model_name='riddle',
            name='answered_by',
            field=models.ManyToManyField(through='riddlr.UserAnswer', to='riddlr.UserProfile'),
        ),
        migrations.AddField(
            model_name='riddle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
