# Generated by Django 2.0.3 on 2018-03-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tries', models.IntegerField()),
                ('correct', models.BooleanField()),
                ('previous_answer', models.CharField(max_length=30)),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddlr.Riddle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddlr.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='riddle',
            name='answered_by',
            field=models.ManyToManyField(through='riddlr.UserAnswer', to='riddlr.UserProfile'),
        ),
    ]
