# Generated by Django 2.0.3 on 2018-03-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0002_auto_20180323_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='difficulty_pt',
            field=models.CharField(default='medium', max_length=10),
        ),
    ]
