# Generated by Django 2.0.3 on 2018-03-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0002_auto_20180308_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='riddle_id',
        ),
        migrations.AddField(
            model_name='riddle',
            name='answers',
            field=models.CharField(default='', max_length=300),
        ),
    ]
