# Generated by Django 2.0.3 on 2018-03-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0003_riddle_difficulty_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
