# Generated by Django 2.0.3 on 2018-03-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0005_riddle_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='answer',
        ),
    ]
