# Generated by Django 2.0.3 on 2018-03-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0006_remove_riddle_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='details',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='num_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='guess_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
