# Generated by Django 2.0.3 on 2018-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0007_auto_20180309_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='riddles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
