# Generated by Django 2.0.3 on 2018-03-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0008_auto_20180316_1337'),
        ('riddlr', '0008_auto_20180316_1342'),
    ]

    operations = [
    ]
