# Generated by Django 2.0.3 on 2018-03-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0009_merge_20180316_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
