# Generated by Django 2.0.3 on 2018-03-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddlr', '0009_merge_20180316_1410'),
        ('riddlr', '0010_remove_userprofile_website'),
    ]

    operations = [
    ]
